### ISSUE TITLE
Just one issue

### ISSUE THREAD

**Issue by n37w0rk** [ghostery/user-agent-ios#1279]
I really would make this my go to browser if there was a sync option to share bookmarks across devices until then I'm using it as a backup to look and Vivaldi

**Comment by chrmod** [comment]
Sadly sync support is not on our roadmap - need to close this issue for now.

To be clear, we very much see a value of sync, this is however a feature that requires a significant investment and introduces running cost (server side infrastructure). 

I would recommend trying our Ghostery extension for Safari as an alternative for Ghostery browser.
